### ISSUE TITLE
Add --stop-timeout to docker run command

### ISSUE THREAD

**Issue by sixcorners** [storj/docs#139]
Instead of putting in the FAQ that we should use -t 300 with docker stop to take down the node for maintenance you should set --stop-timeout in the docker run command so docker takes care of it for you. This also allows tools like watchtower to follow this same procedure.

**Comment by ifraixedes** [comment]
@sixcorners thank you very much for the heads up.
It's definitely a good thing to add and we'll do it.

**Comment by AlexeyALeonov** [comment]
Added. Please, check out

**Comment by sixcorners** [comment]
So.. I added this to mine but it caused watchtower to shut down the storage node..

    time="2020-05-03T00:00:45Z" level=error msg="\"stop timeout\" requires API version 1.25, but the Docker daemon API version is 1.24"

I'm using containrrr/watchtower and docker 18.09.9. idk.. I will look into it next weekend.

**Comment by ifraixedes** [comment]
Not sure if using the `containrrr/watchtowwer` is the issue, but we use our watchtower fork https://github.com/storj/watchtower/tree/v0.3.8-patch to have an image in our docker hub  https://hub.docker.com/r/storjlabs/watchtower

We created that fork because we ran into issues with the original one.
However, we are not keeping it updated with the upstream changes because our goal is to have our own auto-update system to fit better to our requirements and it's something that we have started to work on.

**Comment by sixcorners** [comment]
bummer.
ok well.. your version seems to work. and it does wait five minutes but it seems to ignore --stop-timeout on the container itself. which is better than the one from containrrr.

**Comment by ifraixedes** [comment]
I hope that we'll have an auto-updater mechanism for the docker container soon and we'll be able to stop using watchtower.
Thanks for your patience.
