### ISSUE TITLE
Ticket #15548. Missing mandatory `--not-after=` option in `uplink share`

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/docs#170]
page at https://docs.storj.io/dcs/getting-started/quickstart-uplink-cli/uploading-your-first-object/view-distribution-of-an-object/ needs to be updated. The share command requires an additional command line parameter `--not-after=`

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/90dG8JS6MYLK3MafSLYw/api-reference/uplink-cli/share-command

**Comment by heunland** [comment]
@AlexeyALeonov I have reviewed this and fixed a grammar error, also, I have changed in this section https://docs.storj.io/dcs/getting-started/quickstart-uplink-cli/uploading-your-first-object/view-distribution-of-an-object/ under Access Restrictions,
`NotAfter  : No restriction` to `NotAfter  : disallow access after 2 hours` because the example uplink share command now has specified `--not-after=+2h`

Please check this is correct and then merge it.

**Comment by AlexeyALeonov** [comment]
It should be an exact date. Updated

**Comment by heunland** [comment]
Reviewed and merged
