### ISSUE TITLE
Update Uplink CLI Docs (Server side copy)

### ISSUE THREAD

**Issue by ferristocrat** [storj/docs#194]
**Overview**
With the introduction of Server Side Copy, our `cp` method via the uplink cli now utilizes server side copy -- the docs should reflect this behavior.

**What is the change?**
The following section of the `/uplink-cli/cp-command` doc should be updated: [Copy an object from one location to another in Storj DCS](https://docs.storj.io/dcs/api-reference/uplink-cli/cp-command/#copy-an-object-from-one-location-to-another-in-storj-dcs)

<img width="1426" alt="Screen Shot 2022-05-05 at 11 39 59 AM" src="https://user-images.githubusercontent.com/7063002/166999809-9e313d94-9e97-4696-919f-ecdaaa297a07.png">

**Change 1:**
OLD: 
~~When the cp command is used to copy a file from one Storj DCS location to another Storj DCS location, the CLI will **download** the object from the previous location and **upload** it to a new location.~~
NEW: 
When the cp command is used to copy a file from one Storj DCS location to another Storj DCS location, the object will be copied entirely on the "server" side -- **this will not could against your egress limits, as the object is not being downloaded.**

**Change 2:** 
Remove the yellow notification with the following text: "The download bandwidth will count against your egress limits. You can be charged for egress traffic according to your [tariff plan](https://docs.storj.io/dcs/api-reference/uplink-cli/cp-command/broken-reference)."

**Comment by ferristocrat** [comment]
@iglesiasbrandon - Can you fact check me on the above documentation changes?

**Comment by iglesiasbrandon** [comment]
When the cp command is used to copy a file from one location to another, the object will be copied entirely on the "server" side -- this action does not incur egress fees and does not affect your project's egress limits.

**Comment by heunland** [comment]
Are you saying the regular cp command will be doing server side copy now by default when used to copy a file from one Storj DCS location to another Storj DCS location? 

Yesterday @littleskunk did a demo and I was under the impression that this would work with a special command involving something like s3api? Or is this something different? Does this also means that encryption would not be client side? If so a caveat about that should be included.

Also afaik v1.54 which should include https://github.com/storj/storj/commit/dd6aac9 has not been released yet so I think we should not publish a change to the doc regarding server side copy until it is actually in production.

**Comment by AlexeyALeonov** [comment]
@littleskunk mention that this feature should be enabled on the production satellites already and it should be enabled soon on edge services as well.
So, `uplink cp sj://bucket1/object sj://bucket2/object` should now perform a server-side copy.

And after it would be enabled on edge services, it also start to work with S3-compatible tools, include `aws s3api cp`.

**Comment by AlexeyALeonov** [comment]
Right now it's not the case for both tooling
```
./uplink cp sj://test/uplink sj://test/uplink2
upload sj://test/uplink to sj://test/uplink2
1.81 MiB / 20.43 MiB [------>______________________________________________________________________] 8.85% 2.14 MiB p/s
```

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/1uLHloFD2CMiNxhcq2WL/api-reference/uplink-cli/cp-command
is ready for review and merge

**Comment by heunland** [comment]
Review (see comments in gitbook):
1) cp usage under windows shows [flags] to be specified before SOURCE and DESTINATION rather than after like for Linux and macOS (Windows command in https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/1uLHloFD2CMiNxhcq2WL/api-reference/uplink-cli/cp-command) 
the example usage in https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/1uLHloFD2CMiNxhcq2WL/api-reference/uplink-cli/cp-command#copy-a-local-file-into-a-bucket-with-an-expiration-date actually shows the flag is specified after SOURCE and before DESTINATION for all operating systems, but later another example for [Copying an object with parallelism](https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/1uLHloFD2CMiNxhcq2WL/api-reference/uplink-cli/cp-command#copy-an-object-with-parallelism) shows the flag after DESTINATION. So I suppose it doesn't matter where you place the flag but at least we should show it in the same order in the first definition for `cp` usage for all operating systems.

2) In the 3 examples that have output images, these output images are not loading for me. Please re-upload all images

This can be merged after fixing 1) and 2)

**Comment by AlexeyALeonov** [comment]
I fixed the usage tooltip, however these flags could be specified in any order. They should be after the command though.

**Comment by heunland** [comment]
The changes have been merged after final review.
