### ISSUE TITLE
Add intro to photos+ how to

### ISSUE THREAD

**Issue by dominickmarino** [storj/docs#206]
Article - https://docs.storj.io/dcs/how-tos/photos+-integration-guide/

Intro: iOS/Android App. Store and manage your photos and videos in your own cloud storage account. You can use Photos+ with StorjDCS S3-compatible storage.

**Main Site**
https://photosplus.app/
**Apple App Store**
https://apps.apple.com/us/app/photos-cloud-library/id1310744251
**Google Play Store**
https://play.google.com/store/apps/details?id=com.pixegram.photosplus&hl=en_US&gl=US

**Comment by AlexeyALeonov** [comment]
What should be done here?
The doc already published

**Comment by heunland** [comment]
At the beginning, we need a short intro paragraph that describes what the Photo+ app is good for. Dominick has put the suggested intro text in his comment above: ¨iOS/Android App. Store and manage your photos and videos in your own cloud storage account. You can use Photos+ with StorjDCS S3-compatible storage.¨

Below that and before the step by step instructions start, there should be a sentence telling the user where they can download the app, with the url to the website https://photosplus.app/  - I don´t think we need separate links for the actual downloads for iOS and Android since they are right there on the Photos+ download page.

**Comment by AlexeyALeonov** [comment]
https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/fEXSaJerlZeosDnbfXpW/how-tos/photos+-integration-guide
Ready for merge and review

**Comment by heunland** [comment]
Corrected some grammar and style. This section has been merged.
