### ISSUE TITLE
Add How-To for Comet Backup

### ISSUE THREAD

**Issue by wthorp** [storj/docs#212]
https://cometbackup.com/

**Comment by amozoss** [comment]
Ready for review https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LmlDzFHYn9g_f2QxmPe-887967055/~/changes/V2cEhatsJAAgLBsnSsoX/how-tos/cometbackup-integration-guide#configuring-the-storj-access-key

**Comment by heunland** [comment]
Since the section was already merged before review was done, I am leaving my comments for things that need fixing here:

section `Create a Storj bucket`

- ¨bucket¨ in that title should be capitalized

-  `4. Select “Continue` and `6. Select “Continue`  are missing the closing quote

section `Create Storj access key`

- ¨access¨ and ¨key¨ should be capitalized in the title
-  `4. Name: The name of the access g (e.g. Comet)`  missing completing the word ¨grant¨  instead of just ¨g¨

**Comment by amozoss** [comment]
Published https://docs.storj.io/dcs/how-tos/cometbackup-integration-guide/

**Comment by stoweandi** [comment]
Note: migrated to Archbee
